import '@/styles/globals.css';
import React from 'react';
import NavigationBar from '@/components/common/NavigationBar';
import ModalContainer from '@/components/modal/ModalContainer';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <NavigationBar>{children}</NavigationBar>
        <ModalContainer />
      </body>
    </html>
  );
}
