import '../../styles/globals.css';
import React from 'react';
import NavigationBar from 'src/components/common/NavigationBar';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <NavigationBar>{children}</NavigationBar>
      </body>
    </html>
  );
}
